keybinding:
  universal:
    focusMainView: '<tab>'
    nextBlock-alt2: <disabled>
promptToReturnFromSubprocess: false
customCommands:
  - key: "A"
    context: "files"
    description: "AI commit with draft"
    loadingText: "Generating commit message..."
    prompts:
      - type: "input"
        title: "Prompt for commit message draft"
        key: "Draft"
    command: "git ai {{.Form.Draft | quote}}"
    output: terminal
gui:
  scrollHeight: 30
  authorColors:
    'Taiki Ono': 'red'
  theme:
    activeBorderColor:
      - "#FF79C6"
      - bold
    inactiveBorderColor:
      - "#BD93F9"
    searchingActiveBorderColor:
      - "#8BE9FD"
      - bold
    optionsTextColor:
      - "#6272A4"
    selectedLineBgColor:
      - "#6272A4"
    inactiveViewSelectedLineBgColor:
      - bold
    cherryPickedCommitFgColor:
      - "#6272A4"
    cherryPickedCommitBgColor:
      - "#8BE9FD"
    markedBaseCommitFgColor:
      - "#8BE9FD"
    markedBaseCommitBgColor:
      - "#F1FA8C"
    unstagedChangesColor:
      - "#FF5555"
    defaultFgColor:
      - "#F8F8F2"
